// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopHundredTrades.Data;

#nullable disable

namespace TopHundredTrades.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240317212733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("TopHundredTrades.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("ask")
                        .HasColumnType("REAL");

                    b.Property<float>("bid")
                        .HasColumnType("REAL");

                    b.Property<int>("canceled_trade_condition_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("exchange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("quote_datetime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("trade_condition_id")
                        .HasColumnType("INTEGER");

                    b.Property<float>("trade_price")
                        .HasColumnType("REAL");

                    b.Property<int>("trade_size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("underlying_symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
